### ISSUE TITLE
Tracking peaple

### ISSUE THREAD

**Issue by ARHLANE** [BillZito/kalman#1]
Hello
thank you for sharing your code
I have a project on the follow-up of persons and I have already implement the detection(with hog), now I need a tracking algorithm (Kalman) is that there is the possibility to use your code for my case (with a capture camera) ?

**Comment by BillZito** [comment]
The current algorithms are for lidar and radar data, so I'm not sure that it will be useful for your situation. But definitely feel free to clone it and use it as you'd like. Wish you luck!
